name: .NET Core

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: windows-latest
    name: Update package

    steps:
    - name: Restore repository
    - uses: actions/checkout@v2
      
    - name: Use .NET Core 3.1.301
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    
    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      run: |
        dotnet build MathCore.WPF.Styles/MathCore.WPF.Styles.csproj -c Release --no-restore
        dotnet build Tests/MathCore.WPF.Styles.WPFTests/MathCore.WPF.Styles.WPFTests.csproj -c Release --no-restore
      
    - name: Run Test
      run: dotnet test Tests/MathCore.WPF.Styles.WPFTests/MathCore.WPF.Styles.WPFTests.csproj --no-restore --verbosity normal
      
    - name: Packing
      run: dotnet pack MathCore.WPF.Styles/MathCore.WPF.Styles.csproj --no-build -c Release -v q
       
    - name: Publishing
      run: dotnet nuget push MathCore.WPF.Styles/bin/Release/*.nupkg -s https://api.nuget.org/v3/index.json -n --skip-duplicate -k ${{ secrets.NuGetApiKey }}
