name: Publish NuGet.org

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: windows-latest
    name: Update package

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
        
      - name: Building
        run: |
          dotnet build MathCore.WPF.Styles\MathCore.WPF.Styles.csproj -c Release --nologo
          dotnet build Tests\MathCore.WPF.Styles.Tests\MathCore.WPF.Styles.Tests.csproj -c Release --nologo
          
      - name: Testing
        run: dotnet test Tests\MathCore.WPF.Styles.Tests\MathCore.WPF.Styles.Tests.csproj --nologo
        
      - name: Packing
        run: dotnet pack MathCore.WPF.Styles\MathCore.WPF.Styles.csproj --no-build -c Release -v q
        
      - name: Publishing NuGet
        run: dotnet nuget push "**/*.nupkg" --skip-duplicate -k ${{ secrets.NuGetApiKey }} -s https://api.nuget.org/v3/index.json
      
      - name: Publishing GitHub
        run: dotnet nuget push "**/*.nupkg" --skip-duplicate -k ${{secrets.GITHUB_TOKEN}} -s https://nuget.pkg.github.com/Infarh/index.json
